### ISSUE TITLE
Twitch / YouTube integration

### ISSUE THREAD

**Issue by uaon** [7Cav/project-items#16]
https://www.twitch.tv/7thcavalrygamingregiment
https://www.youtube.com/user/7CavGaming

- work on integrating livestreams to be showcased on website.
- api / webhooks for notifications via discord and other mediums when a streamer goes live.
- showcasing our videos on the website either by embed or other means.
- providing documentation on how to integrate channels for them to be showcased by our organization.

**Comment by SyniRon** [comment]
Moved this back to todo for now. DYNO bot can handle the stream announcement to discord, recommend that portion of this be assigned to DYNO bot setup https://github.com/7Cav/project-items/issues/27

I was investigating a few xenforo addons yesterday that can provide some nice sidebar embeds for relevant twitch streams/youtube videos. Will have to brainstorm how we want to proceed on this.
