### ISSUE TITLE
discord bot - features

### ISSUE THREAD

**Issue by uaon** [7Cav/project-items#17]
adding additional features to our discord bot other than just roles by emoji.
- allow for the bot to greet new users with a templated message.
- a bot that removes cav-related roles to force people to sync with forums to maintain them.

**Comment by uaon** [comment]
Somewhat related to endpoints for API
https://github.com/7Cav/api/issues/3#issue-927024749

**Comment by SyniRon** [comment]
Working on detecting new users and sending templated message.

1. Will have template sample by tomorrow.
2. Will have New User Detection and Message Sending function by end of week.

Trying to brainstorm ideas for second necessity. Thinking something like a manual sync option that would use the newly mentioned endpoint. I'm not sure how else to get any event trigger for spawning a sync action other than manual sync

**Comment by SyniRon** [comment]
Added commits to https://github.com/7Cav/cavbot to add the new user message functionality. Need to work on verbage.
