### ISSUE TITLE
7cav API Endpoints / XF DB entry lookups - Personnel mgmt.

### ISSUE THREAD

**Issue by uaon** [7Cav/project-items#19]
Additional Endpoints for the 7cav api for reporting needs.
- Time in Service,
- Time in Grade.
- PAF Logs entries
- metadata / notes on members for S1 backside.
- additional "custom fields" a way to pull or use that data for misc needs.
Some of these exist but are not realized in use cases. 
Focusing on the main problem we don't have a CRUD option available to manage personnel in ways of adding additional information to them that can be seen by departments who instead resort to spreadsheets to formulate where that user is in a defined process for their function.

**Comment by Jarvvski** [comment]
I can take this one on, as I think I’ve got the most SA on the API and related schemas within XF & rosters
