### ISSUE TITLE
Service-Level-Configs redone

### ISSUE THREAD

**Issue by uaon** [7Cav/project-items#20]
SLC in its infancy was for storing configurations and scripts for purposes of our windows / linux servers.
now its a mess of docker images, legacy scripts and a directory mess.

Some spring cleaning is in order.
- restructure the directory so its more in-line with current practices
- update the readme with relevant information, purge all else.
- remove the wiki items, we dont use that anymore.
- re-evaluate if mod configurations will be done via eggs or via json/yaml
- keep tracking on pterodactyl updates if/when they switch to yaml.

**Comment by SyniRon** [comment]
Restructure completed. 
Readme updated.
Removed not-relevant wiki items and updated arma3 wiki entry.
Mod configs will continue being done via json for now, potential for re-evaluation in the future.
